{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redash-searcher.fullname" . }}
  labels:
    {{- include "redash-searcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.redashApiKey }}
  REDASH_API_KEY: {{ .Values.secrets.redashApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.opensearchUsername }}
  OPEN_SEARCH_USERNAME: {{ .Values.secrets.opensearchUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.opensearchPassword }}
  OPEN_SEARCH_PASSWORD: {{ .Values.secrets.opensearchPassword | b64enc | quote }}
  {{- end }}
{{- end }}
