{{- if .Values.sync.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redash-searcher.sync.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: sync
    {{- include "redash-searcher.labels" . | nindent 4 }}
  {{- with .Values.sync.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
